apiVersion: apps/v1
kind: Deployment
metadata:
  name: convertor
spec:
  selector:
    matchLabels:
      app: convertor
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 8
  template:
    metadata:
      labels:
        app: convertor
    spec:
      containers:
        - name: convertor
          image: himmathur55/convertor:latest
          envFrom:
            - configMapRef:
                name: convertor-configmap
            - secretRef:
                name: convertor-secret
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
